server:
  port: 8080

spring:
  application:
    name: SWD392_BE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swd392_be?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "${BASE_URL:http://localhost:8080}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  #App Password
  mail:
    host: smtp.gmail.com
    port: 587
    username: datnpse182125@fpt.edu.vn
    password: cndkwqjqfraoyjlm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#    cndkwqjqfraoyjlm

# JWT Configuration
secret:
  jwt:
    secret-key: SWD392_BE_JWT_SecretKey_2026_abcdefghijklmnopqrstuvwxyz1234567890VerySecureKey!
    expiration-time: 3600000 # 1 day in milliseconds
    reset-expiration-time: 900000   # 15 phút

# App Configuration
app:
  oauth2:
    authorized-redirect-uri: ${FRONTEND_URL:http://localhost:3000}/auth/callback
  openapi:
    dev-url: http://localhost:8080
    prod-url: ${BACKEND_PRODUCT_URL:http://localhost:8080}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
